apiVersion: v1
kind: Service
metadata:
  name: ht-sb-frontend-service
  namespace: ht-sb
spec:
  selector:
    app: ht-sb-frontend
  ports:
  - port: 3005
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP